homework 4 all tasks
AlexandrBelan/JS_HW pull request #2
Opened 2024-05-26 18:10 UTC by AlexandrBelan

homework 4 all tasks comleted

2024-05-26 19:26 UTC, anatoly-karpovich requested changes

2024-05-26 19:26 UTC, anatoly-karpovich commented on JS_lesson4/Task2.js
> +        case Number.isNaN(Number(age)): {
I belive this case should be under IF statement BEFORE switch to cut invalid data. And then to work in switch with only valid numbers

2024-05-26 19:26 UTC, anatoly-karpovich commented on JS_lesson4/Task2.js
> +        case Number(age) >= age_2 && Number(age) < age_3: {
Number(age) is duplicated in several rows. It is better to place this convertation BEFORE switch block

2024-05-26 19:26 UTC, anatoly-karpovich commented on JS_lesson4/Task3.js
> +    case isNaN(age): {
Same as for previous task, i belive that isNaN check should be performed before switch

2024-05-26 19:49 UTC, VladimirLQA requested changes

2024-05-26 19:49 UTC, VladimirLQA commented on JS_lesson4/Task2.js
> +    }
What is the purpose of declaring a string value in the `age` constant and then converting it to a number?

Pay attention to the description of the 2nd task - we only need to check the type of the value, if the value type is not a number, throw an error

Please provide a solution to the 2nd problem using the `if...else` statement.

Add a separate solution for the 3rd problem

2024-05-26 19:49 UTC, VladimirLQA commented on JS_lesson4/Task3.js
> +const age = Number(prompt(`Введи возраст`));
No need to convert input to a number, we should check it with provided conditions

2024-05-26 19:49 UTC, VladimirLQA commented on JS_lesson4/Task2.js
> +        case Number.isNaN(Number(age)): {
For 3-rd task add checks for `falsy` values

2024-05-27 09:16 UTC, anatoly-karpovich approved these changes

2024-05-27 09:16 UTC, anatoly-karpovich commented on JS_lesson4/Task3.js
> +switch (true) {
Seems like you need to convert age to number (cause prompt returns string) just bedore switch statement:
age = +age

Cause now you are using string value comparing with numbers

2024-05-27 09:23 UTC, VladimirLQA approved these changes

2024-05-27 11:38 UTC, merged