all tascs homework 5
AlexandrBelan/JS_HW pull request #3
Opened 2024-05-29 15:48 UTC by AlexandrBelan

Everything works locally

2024-05-29 21:18 UTC, VladimirLQA commented on JS_lesson5/Task3.js
> +console.log(resultStr)
```suggestion
for (let i = 0; i < str.length; i++) {
    index = alphabet.indexOf(str[i].toLowerCase())
    newIndex = index + offset;
    if (index === 0 && offset < 0) {
        newIndex = alphabet.length -1;
    }
    if (index === alphabet.length -1 && offset > 0) {
        newIndex = 0;
    }
    if (str[i] !== alphabet[index]){
        resultStr +=  alphabet[newIndex].toUpperCase();
    } else {
        index += offset;
        resultStr += alphabet[newIndex];
    }
}
console.log(resultStr)
```

2024-05-29 21:34 UTC, VladimirLQA requested changes

2024-05-29 21:34 UTC, VladimirLQA commented on JS_lesson5/Task2.js
> +// 2. Сделать из "*" в консоли равнобедренный треугольник и ромб
2 in 1 ? :)
Need left side of diamond )
![image](https://github.com/AlexandrBelan/JS_HW/assets/103571439/b9036a6c-085f-4343-9c44-fa84ddd97f12)

2024-05-29 23:39 UTC, anatoly-karpovich requested changes

2024-05-29 23:39 UTC, anatoly-karpovich commented on JS_lesson5/Task2.js
> +while (true) {
It is an infinity loop. Need a clear way to break a loop

2024-05-30 15:52 UTC, VladimirLQA requested changes

2024-05-30 15:52 UTC, VladimirLQA commented on JS_lesson5/Task3.js
> +}
```suggestion
const word = 'Wummermustdie';
const consonants = 'qwrtpsdfghjklzxcvbnm';
const vowels = 'eyuioa';
let splitWord = word.toLowerCase().split('');
let countConsonants = 0;
let countVowels = 0;
for (let i = 0; i < word.length; i++) {
    if (consonants.includes(splitWord[i])) {
        countConsonants++;
    } else {
        countVowels++;
    }
}
```

2024-05-30 15:52 UTC, VladimirLQA commented on JS_lesson5/Task3.js
> +// console.log(`word contains ${containsNum} vowels and ${consonantsNum} consonants`);
Try to test this example `ab21`

2024-05-30 20:24 UTC, VladimirLQA commented on JS_lesson5/Task3.js
> +const str = 'abcZ';
Try to modify this solution to handle such case `ab 1Z` - leave space and number in the result line

2024-05-31 08:45 UTC, anatoly-karpovich approved these changes

2024-05-31 09:02 UTC, VladimirLQA approved these changes

2024-05-31 09:07 UTC, merged