all tascs homework 6
AlexandrBelan/JS_HW pull request #4
Opened 2024-06-03 11:15 UTC by AlexandrBelan

all tascs homework 6, I hope everything is ok.

2024-06-03 19:48 UTC, VladimirLQA requested changes

2024-06-03 19:48 UTC, VladimirLQA commented on JS_lesson6/Task2.js
> +    }
```suggestion
    return word === word.split('').reverse().join(''));
```

2024-06-03 19:48 UTC, VladimirLQA commented on JS_lesson6/Task2.js
> +    return(uniqValues);
```suggestion
    return [...new Set(values)];
```

2024-06-03 19:48 UTC, VladimirLQA commented on JS_lesson6/Task2.js
> +    const maxLength = Math.max(...lengthWord);
```suggestion
    const maxLength = Math.max(...arrayWords.map(word => word.length));
```

2024-06-03 19:48 UTC, VladimirLQA commented on JS_lesson6/Task2.js
> +    }
```suggestion
    const resultWords = arrayWords.filter(word => word.length === maxLength);
```

2024-06-03 19:48 UTC, VladimirLQA commented on JS_lesson6/Task2.js
> +    console.log(resultWords);
use `return` key word for functions :)

2024-06-03 19:48 UTC, VladimirLQA commented on JS_lesson6/Task3.js
> +    let arrayDigitsString = num.toString().split('');
Convert to string without splitting if you use `for...of` loop, because both arrays and strings are iterables in JS

2024-06-03 19:48 UTC, VladimirLQA commented on JS_lesson6/Task3.js
> +    alphabet = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'];
Explicit variable declaration for `alphabet`

2024-06-03 19:48 UTC, VladimirLQA commented on JS_lesson6/Task3.js
> +        return (resultStr);
```suggestion
        return noDouble(resultStr);
    } else {
        return resultStr;
```

2024-06-04 08:30 UTC, AlexandrBelan commented
I took into account all Vlodimir’s comments and implemented the case for Z in Task 3

2024-06-04 08:55 UTC, anatoly-karpovich requested changes

2024-06-04 08:55 UTC, anatoly-karpovich commented on JS_lesson6/Task2.js
> +const competitorPizzas = ['Peperoni', 'Caprichosa', 'Diablo', '4 cheeses', 'hawai']
According to this array we have pizzas in different registers. Need to transform to similar register when checking)

E.g. map competitor pizzas to low register in function

2024-06-04 09:32 UTC, VladimirLQA approved these changes

2024-06-04 11:23 UTC, AlexandrBelan commented on JS_lesson6/Task3.js
> +        return (resultStr);
implemented via map and filter

2024-06-04 11:27 UTC, AlexandrBelan commented
third try, comments taken into account Task2.

2024-06-04 11:55 UTC, anatoly-karpovich approved these changes

2024-06-04 11:58 UTC, merged